name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SECRET: ${{secrets.GCLOUD_AUTH}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Google Cloud SDK
        run: |
          # Add the Google Cloud SDK distribution URI as a package source
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      
          # Add the GPG key for the Google Cloud SDK
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      
          # Update the package list and install the SDK
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Upload files to Google Cloud Storage
        run: |
          echo "${{GOOGLE_SECRET}}" | awk '$1=$1' FS= OFS=" "
          gsutil -m rsync -r .svelte-kit gs://portfolio_bucket_mp

