name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
       #Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies and build project
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      # Authenticate with Google Cloud
      - name: Google Cloud authenticate and setup
        run: |
          echo "${{ secrets.GCLOUD_AUTH}}" | base64 --decode > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project portfolio-442422
    

      
      # Debugging: Verify authentication
      - name: Verify Authentication

        run: gcloud auth list

      # Debugging: List buckets
      - name: List Google Cloud Storage Buckets
        run: gcloud storage buckets list 

      # Debugging: Check bucket permissions
      - name: Check Bucket Access
        run: gsutil ls gs://portfolio_bucket_mp

      # Upload files to Google Cloud Storage
      - name: Upload Files to Google Cloud Storage
        run: |
          gsutil -m rsync -r build gs://portfolio_bucket_mp


      # Set CORS configuration for the bucket
      - name: Set CORS Configuration
        run: |
          echo '[
            {
              "origin": ["*"],
              "method": ["GET", "HEAD", "OPTIONS"],
              "responseHeader": ["Content-Type"],
              "maxAgeSeconds": 3600
            }
          ]' > cors.json
          gsutil cors set cors.json gs://portfolio_bucket_mp


      # Set the bucket's website configuration
      - name: Set Bucket Website Configuration
        run: |
          gcloud storage buckets update gs://portfolio_bucket_mp \
            --web-main-page-suffix index.html \
            --web-error-page index.html